security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
            logout:
                path: admin_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }