controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_products:
    resource: '../src/Controller/Api/ProductController.php'
    type: attribute
    prefix: /api