parameters:
    cottages_data_path: '%kernel.project_dir%/data/dev/cottages.csv'
    bookings_data_path: '%kernel.project_dir%/data/dev/bookings.csv'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true


    App\Service\HomeDataService:
        arguments:
            $cottagesFile: '%cottages_data_path%'

    App\Service\BookingService:
        arguments:
            $bookingsFile: '%bookings_data_path%'