parameters:
    env(APP_ENV): 'dev'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true

    App\Command\InitDataCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags: ['console.command']